import { ObjectId } from "mongodb";

type Post = PostStandalone | PostWithReference;

interface PostBase {
	/**
	 * id of this post, should be auto-generated
	 *
	 * @name _id
	 */
	_id?: ObjectId;
	/**
	 * post references, generated by server
	 *
	 * @name _references
	 */
	_references?: Post[];
	/**
	 * id of the owning user
	 *
	 * @name ownerId
	 */
	ownerId: string;
	/**
	 * message content of this post
	 *
	 * @name content
	 */
	content?: string;
	/**
	 * list of attachments _ids
	 *
	 * @name attachments
	 */
	attachments?: string[];
	/**
	 * Creation timestamp
	 *
	 * @name timestamp
	 */
	timestamp: number;
	/**
	 * list of reactions
	 *
	 * @name reactions
	 */
	reactions?: {
		userId: string;
		emoji: string;
	}[];
}

interface PostStandalone extends PostBase {
	// for typing
	_type: "standalone";
	/**
	 * post visibility
	 *
	 * @name visibility
	 */
	visibility: "all" | "follower" | "self";
}

interface PostWithReference extends PostBase {
	// for typing
	_type: "reference";
	/**
	 * id of the referenced post (basically as a parent post > comment)
	 *
	 * @name referenceId
	 */
	referenceId: string;
}

export type { Post, PostStandalone, PostWithReference };
